<?php
session_start();
require "../config/db.php";
require "../fpdf/fpdf.php";

/* ============================
   ADMIN AUTH CHECK
============================ */
if (!isset($_SESSION['admin_id'])) {
    header("Location: admin_login.php");
    exit();
}

/* ============================
   FETCH ALL TRANSACTIONS
============================ */
$sql = "
    SELECT 
        t.id,
        t.amount,
        t.transaction_type,
        t.created_at,
        t.sender_account,
        t.receiver_account,
        COALESCE(u.fullname,'Deleted User') AS fullname,
        COALESCE(u.status,'deleted') AS status
    FROM transactions t
    LEFT JOIN users u ON t.user_id = u.id
    ORDER BY t.created_at DESC
";

$result = mysqli_query($conn, $sql);
if (!$result) {
    die("Database Error: " . mysqli_error($conn));
}

/* ============================
   PDF GENERATION
============================ */
$pdf = new FPDF();
$pdf->AddPage();

/* Title */
$pdf->SetFont('Arial','B',16);
$pdf->Cell(0,10,'CRDB BANK',0,1,'C');

$pdf->SetFont('Arial','',12);
$pdf->Cell(0,8,'System Transactions Report',0,1,'C');
$pdf->Ln(5);

/* Table header */
$pdf->SetFont('Arial','B',10);
$pdf->Cell(10,8,'ID',1);
$pdf->Cell(35,8,'User',1);
$pdf->Cell(20,8,'Status',1);
$pdf->Cell(25,8,'Type',1);
$pdf->Cell(35,8,'Sender',1);
$pdf->Cell(35,8,'Receiver',1);
$pdf->Cell(25,8,'Amount',1);
$pdf->Cell(30,8,'Date',1);
$pdf->Ln();

/* Table body */
$pdf->SetFont('Arial','',10);

while($row = mysqli_fetch_assoc($result)) {
    $pdf->Cell(10,8,$row['id'],1);
    $pdf->Cell(35,8,$row['fullname'],1);

    /* Status formatting */
    $status = ucfirst($row['status']);
    $pdf->Cell(20,8,$status,1);

    $pdf->Cell(25,8,ucfirst($row['transaction_type']),1);

    $pdf->Cell(35,8,$row['sender_account'] ?: '-',1);
    $pdf->Cell(35,8,$row['receiver_account'] ?: '-',1);

    $pdf->Cell(25,8,number_format($row['amount'],2),1);
    $pdf->Cell(30,8,date("d-M-Y H:i", strtotime($row['created_at'])),1);

    $pdf->Ln();
}

$pdf->Ln(5);
$pdf->Cell(0,8,'Generated by CRDB Online Banking System',0,1,'C');

/* Output PDF in browser */
$pdf->Output("I","CRDB_Admin_Report.pdf");
